// Fallback data so the UI can be developed in the browser without the Tauri
// backend (`npm run dev`). None of it is used in a real build.
import type {
  AppConfig,
  AudioDevice,
  AudioProcess,
  CaptureTarget,
  Clip,
  ClipTrack,
  EncoderInfo,
} from "./types";

export const mockDevices: AudioDevice[] = [
  { id: "out-1", name: "Headphones (Realtek USB Audio)", kind: "output", isDefault: true },
  { id: "out-2", name: "LG HDR 4K (NVIDIA High Definition Audio)", kind: "output", isDefault: false },
  { id: "in-1", name: "Mikrofon (Elgato Wave XLR)", kind: "input", isDefault: true },
  { id: "in-2", name: "Line In (Focusrite Scarlett)", kind: "input", isDefault: false },
];

export const mockProcesses: AudioProcess[] = [
  { pid: 4321, name: "Discord", exe: "Discord.exe" },
  { pid: 8899, name: "Counter-Strike 2", exe: "cs2.exe" },
  { pid: 1122, name: "Spotify", exe: "Spotify.exe" },
  { pid: 7654, name: "Chrome", exe: "chrome.exe" },
];

export const mockTargets: CaptureTarget[] = [
  { kind: "monitor", id: "\\\\.\\DISPLAY1", title: "Monitor 1 — 2560×1440", width: 2560, height: 1440, isPrimary: true, refreshHz: 165 },
  { kind: "monitor", id: "\\\\.\\DISPLAY2", title: "Monitor 2 — 1920×1080", width: 1920, height: 1080, isPrimary: false, refreshHz: 60 },
  { kind: "window", id: "0x00120A", title: "Counter-Strike 2", width: 2560, height: 1440, isPrimary: false, refreshHz: 165 },
];

export const mockEncoders: EncoderInfo[] = [
  { id: "nvenc", name: "NVIDIA NVENC (H.264)", available: true, hardware: true },
  { id: "amf", name: "AMD AMF (H.264)", available: false, hardware: true },
  { id: "qsv", name: "Intel QuickSync (H.264)", available: false, hardware: true },
  { id: "x264", name: "x264 (CPU, Fallback)", available: true, hardware: false },
];

export const mockConfig: AppConfig = {
  recording: {
    targetKind: "monitor",
    targetId: "\\\\.\\DISPLAY1",
    width: 1920,
    height: 1080,
    fps: 60,
    bitrateKbps: 19000,
    quality: 70,
    encoder: "nvenc",
    keyframeSeconds: 2,
  },
  buffer: { autoStart: false, seconds: 120, clipSeconds: 0, memoryMb: 0 },
  sources: [
    {
      id: "src-game",
      label: "Game",
      kind: { type: "process", pid: 8899, mode: "include" },
      enabled: true,
      gainDb: 0,
      muted: false,
      solo: false,
      separateTrack: false,
    },
    {
      id: "src-discord",
      label: "Discord",
      kind: { type: "process", pid: 4321, mode: "include" },
      enabled: true,
      gainDb: -3,
      muted: false,
      solo: false,
      separateTrack: true,
    },
    {
      id: "src-mic",
      label: "Mikrofon",
      kind: { type: "inputDevice", deviceId: "in-1" },
      enabled: true,
      gainDb: 2,
      muted: false,
      solo: false,
      separateTrack: true,
    },
  ],
  clipDir: "C:\\Users\\fabia\\Videos\\ClippiBoy",
  saveClipHotkey: "Ctrl+Shift+S",
  toggleBufferHotkey: "Ctrl+Shift+B",
  screenshotHotkey: "Ctrl+Shift+P",
  autoStartWithWindows: false,
  onlyBufferInGame: true,
  overlay: {
    enabled: true,
    onClipSaved: true,
    onBufferToggle: true,
    onError: true,
    onScreenshot: true,
    corner: "bottomRight",
    durationMs: 3500,
    monitor: null,
    followActiveScreen: false,
  },
  trayHintShown: false,
  control: { enabled: true, port: 47653, token: "mock-token" },
};

export const mockClips: Clip[] = [
  {
    id: "c1",
    path: "C:\\Users\\fabia\\Videos\\ClippiBoy\\cs2_2026-08-17_22-14-03.mp4",
    createdAt: Date.now() - 1000 * 60 * 12,
    durationMs: 32_000,
    game: "Counter-Strike 2",
    width: 1920,
    height: 1080,
    sizeBytes: 168_000_000,
    thumbPath: null,
    title: "Ace on Mirage",
    description: "Last round, 1v3 after the retake.",
    favorite: true,
    edit: null,
    original: null,
    originalAvailable: false,
    screenshot: false,
  },
  {
    id: "c2",
    path: "C:\\Users\\fabia\\Videos\\ClippiBoy\\cs2_2026-08-17_21-48-51.mp4",
    createdAt: Date.now() - 1000 * 60 * 60 * 3,
    durationMs: 60_000,
    game: "Counter-Strike 2",
    width: 1920,
    height: 1080,
    sizeBytes: 305_000_000,
    thumbPath: null,
    title: null,
    description: null,
    favorite: false,
    edit: null,
    original: null,
    originalAvailable: false,
    screenshot: false,
  },
  {
    id: "c3",
    path: "C:\\Users\\fabia\\Videos\\ClippiBoy\\nohesi_2026-08-16_02-11-20.mp4",
    createdAt: Date.now() - 1000 * 60 * 60 * 26,
    durationMs: 18_500,
    game: "No Hesi",
    width: 1920,
    height: 1080,
    sizeBytes: 94_000_000,
    thumbPath: null,
    title: null,
    description: null,
    favorite: false,
    edit: null,
    original: null,
    originalAvailable: false,
    screenshot: false,
  },
  // The gallery has to survive the bad case too: one clip with no game and three
  // misdetections from before the stricter title check — that is what shows
  // whether the filter bar truncates, scrolls and can be tidied up. The German
  // window titles are deliberate: they come from a German-locale Windows.
  {
    id: "c4",
    path: "C:\\Users\\fabia\\Videos\\ClippiBoy\\clip_2026-08-15_19-02-44.mp4",
    createdAt: Date.now() - 1000 * 60 * 60 * 30,
    durationMs: 24_000,
    game: null,
    width: 2560,
    height: 1440,
    sizeBytes: 142_000_000,
    thumbPath: null,
    title: null,
    description: null,
    favorite: false,
    edit: null,
    original: null,
    originalAvailable: false,
    screenshot: false,
  },
  ...[
    "(102) WIR MÜSSEN PAYEN - YouTube – Opera",
    "C:\\Users\\fabia\\projects\\clippiboy\\synctest.mp4",
    "Snipping Tool Überlagerung",
  ].map((game, i) => ({
    id: `c${5 + i}`,
    path: `C:\\Users\\fabia\\Videos\\ClippiBoy\\clip_2026-08-1${i}_08-30-00.mp4`,
    createdAt: Date.now() - 1000 * 60 * 60 * (40 + i * 5),
    durationMs: 12_000 + i * 3000,
    game,
    width: 1920,
    height: 1080,
    sizeBytes: 60_000_000,
    thumbPath: null,
    title: null,
    description: null,
    favorite: false,
    edit: null,
    original: null,
    originalAvailable: false,
    screenshot: false,
  })),
  ...["Counter-Strike 2", null].map((game, i) => ({
    id: `s${1 + i}`,
    path: `C:\\Users\\fabia\\Videos\\ClippiBoy\\shot_2026-08-2${i}_19-04-1${i}.png`,
    createdAt: Date.now() - 1000 * 60 * (30 + i * 90),
    // A still has no length, and the gallery shows the camera instead.
    durationMs: 0,
    game,
    width: 3840,
    height: 2160,
    sizeBytes: 9_400_000 - i * 1_200_000,
    thumbPath: null,
    title: i === 0 ? "Scoreboard" : null,
    description: null,
    favorite: false,
    edit: null,
    original: null,
    originalAvailable: false,
    screenshot: true,
  })),
];

/** Without a backend there are no real audio tracks — the mixer should still be there. */
export const mockTracks: ClipTrack[] = [
  { index: 0, label: "Main mix", channels: 2, previewPath: "mock/0.m4a" },
  { index: 1, label: "Discord", channels: 2, previewPath: "mock/1.m4a" },
  { index: 2, label: "Mikrofon", channels: 2, previewPath: "mock/2.m4a" },
];
